import type { Config } from "tailwindcss";

// 컬러/타이포/spacing 토큰은 Stitch가 생성한 project_brief_precision_cnc.md 기반 목업의
// tailwind.config 값을 그대로 이식한 것 (Material 3 스타일 시맨틱 네이밍)
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#341100",
        primary: "#000000",
        "surface-bright": "#f6fafe",
        "on-tertiary": "#ffffff",
        "surface-variant": "#dfe3e7",
        "surface-container-highest": "#dfe3e7",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-fixed-variant": "#783200",
        "on-surface-variant": "#45464d",
        "tertiary-fixed-dim": "#ffb690",
        "inverse-surface": "#2c3134",
        "surface-container": "#eaeef2",
        tertiary: "#000000",
        "on-tertiary-container": "#d95f00",
        "on-error-container": "#93000a",
        "surface-container-low": "#f0f4f8",
        "on-background": "#171c1f",
        "surface-dim": "#d6dade",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed-dim": "#b7c8e1",
        outline: "#76777d",
        "inverse-primary": "#bec6e0",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#c6c6cd",
        "error-container": "#ffdad6",
        secondary: "#505f76",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#565e74",
        error: "#ba1a1a",
        background: "#f6fafe",
        "surface-container-high": "#e4e9ed",
        "on-secondary-container": "#54647a",
        "secondary-container": "#d0e1fb",
        surface: "#f6fafe",
        "on-surface": "#171c1f",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed": "#ffdbca",
        "on-primary-container": "#7c839b",
        "inverse-on-surface": "#edf1f5",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "safety-orange": "#FF6B00",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "96px",
        base: "8px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)"],
        "technical-data": ["var(--font-geist)"],
        "headline-xl": ["var(--font-geist)"],
        "headline-lg": ["var(--font-geist)"],
        "headline-md": ["var(--font-geist)"],
        "body-md": ["var(--font-inter)"],
        "label-sm": ["var(--font-geist)"],
      },
      // fontSize는 전부 clamp()로 유동 타이포그래피 처리 — 375px~1280px 뷰포트 사이에서
      // min~max 값 사이를 연속적으로 스케일링 (브레이크포인트에서 뚝뚝 끊기지 않음)
      fontSize: {
        "body-lg": ["clamp(1rem, 0.948rem + 0.22vw, 1.125rem)", { lineHeight: "1.6", fontWeight: "400" }],
        "technical-data": ["clamp(0.75rem, 0.698rem + 0.22vw, 0.875rem)", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-xl": ["clamp(2rem, 1.586rem + 1.77vw, 3rem)", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["clamp(1.5rem, 1.293rem + 0.88vw, 2rem)", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["clamp(1.25rem, 1.146rem + 0.44vw, 1.5rem)", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["clamp(0.875rem, 0.823rem + 0.22vw, 1rem)", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["clamp(0.625rem, 0.573rem + 0.22vw, 0.75rem)", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
